const imagesDishes: { [key: string]: any } = {
    "Apple Cake": require("../../assets/img/dishes/AppleCake.png"),
    "AvocadoToast": require("../../assets/img/dishes/AvocadoToast.png"),
    "Baccalà alla Livornese": require("../../assets/img/dishes/BaccalaLivornese.png"),
    "Baccalà alla Vicentina": require("../../assets/img/dishes/BaccalaVicentina.png"),
    "Bagel with Lox and Cream Cheese": require("../../assets/img/dishes/Bagel.png"),
    "Baked Fish": require("../../assets/img/dishes/BakedFish.png"),
    "Baked Salmon": require("../../assets/img/dishes/BakedSalmon.png"),
    "Bistecca alla Fiorentina": require("../../assets/img/dishes/BisteccaFiorentinaVerdure.png"),
    "Bistecca alla Fiorentina with potatoes": require("../../assets/img/dishes/BisteccaFiorentinaPotatoes.png"),
    "Branzino alla Griglia": require("../../assets/img/dishes/BranzinoGriglia.png"),
    "Bruschetta al Pomodoro": require("../../assets/img/dishes/BruschettaPomodoro.png"),
    "Cacciatora di Cinghiale": require("../../assets/img/dishes/CacciatoraCinghiale.png"),
    "Caponata": require("../../assets/img/dishes/Caponata.png"),
    "Caponata Siciliana": require("../../assets/img/dishes/CaponataSiciliana.png"),
    "CapreseSalad": require("../../assets/img/dishes/CapreseSalad.png"),
    "Chicken Cacciatora": require("../../assets/img/dishes/ChickenCacciatora.png"),
    "Chocolate Cake": require("../../assets/img/dishes/ChocolateCake.png"),
    "Chocolate Ice Cream": require("../../assets/img/dishes/ChocolateIceCream.png"),
    "Clams Linguine": require("../../assets/img/dishes/ClamsLinguine.png"),
    "Cotechino con Lenticchie": require("../../assets/img/dishes/CotechinoLenticchie.png"),
    "Cotoletta alla Milanese": require("../../assets/img/dishes/CotolettaMilanese.png"),
    "Cozze alla Marinara": require("../../assets/img/dishes/CozzeMarinara.png"),
    "Creamy Pumpkin Soup": require("../../assets/img/dishes/CreamyPumpkinSoup.png"),
    "Crispy Pork Belly": require("../../assets/img/dishes/CispyPorkBelly.png"),
    "Croissant alla Marmellata": require("../../assets/img/dishes/CroissantMarmellata.png"),
    "Croissant di Mele": require("../../assets/img/dishes/CroissantMele.png"),
    "Croque-Monsieur": require("../../assets/img/dishes/CroqueMonsieur.png"),
    "Crostata al Limone": require("../../assets/img/dishes/CrostataLimone.png"),
    "Crostata di Frutta": require("../../assets/img/dishes/CrostataFrutta.png"),
    "Crostata di Mele": require("../../assets/img/dishes/CrostataMele.png"),
    "Crostini con Fegato": require("../../assets/img/dishes/CrostiniFegato.png"),
    "Cucumber Salad": require("../../assets/img/dishes/CucumberSalad.png"),
    "Eggplant Parmigiana": require("../../assets/img/dishes/EggplantParmigiana.png"),
    "Eggs Florentine": require("../../assets/img/dishes/EggsFlorentine.png"), 
    "Fennel Salad": require("../../assets/img/dishes/FennelSalad.png"),
    "Filetto di Manzo al Pepe Verde": require("../../assets/img/dishes/FilettoManzo.png"),
    "Fish Soup": require("../../assets/img/dishes/FishSoup.png"),
    "Fonduta Valdostana": require("../../assets/img/dishes/FondutaValdostana.png"),
    "Fried Seafood": require("../../assets/img/dishes/FriedSeafood.png"),
    "Fried Squid": require("../../assets/img/dishes/FriedSquid.png"),
    "Frittata with Asparagus": require("../../assets/img/dishes/FrittataAsparagus.png"),
    "Frittata with Mushrooms": require("../../assets/img/dishes/FrittataMushrooms.png"),
    "Frittata with Spinach": require("../../assets/img/dishes/FrittataSpinach.png"),
    "Frittata with Zucchini": require("../../assets/img/dishes/FrittataZucchini.png"),
    "Fruit Salad": require("../../assets/img/dishes/FruitSalad.png"),
    "Gnocchi al Pesto": require("../../assets/img/dishes/GnocchiPesto.png"),
    "Gnocchi al Pomodoro": require("../../assets/img/dishes/GnocchiPomodoro.png"),
    "Granola Parfait": require("../../assets/img/dishes/GranolaParfait.png"),
    "Green Lasagna": require("../../assets/img/dishes/GreenLasagna.png"),
    "Grilled Meat with Garlic": require("../../assets/img/dishes/GrilledMeatGarlic.png"),
    "Grilled Meat with Potatoes": require("../../assets/img/dishes/GrilledMeatPotatoes.png"),
    "Grilled Meat with Vegetables": require("../../assets/img/dishes/GrilledMeatVegetables.png"),
    "Grilled Octopus": require("../../assets/img/dishes/GrilledOctopus.png"),
    "Grilled Polenta": require("../../assets/img/dishes/GrilledPolenta.png"),
    "Grilled Salmon": require("../../assets/img/dishes/GrilledSalmon.png"),
    "Grilled Vegetables": require("../../assets/img/dishes/GrilledVegetables.png"),
    "Hazelnut Cake": require("../../assets/img/dishes/HazelnutCake.png"),
    "Hearty Bean Soup": require("../../assets/img/dishes/HeartyBeanSoup.png"),
    "Hearty Lentil Soup": require("../../assets/img/dishes/HeartyLentilSoup.png"),
    "Lasagna al Ragù": require("../../assets/img/dishes/LasagnaRagu.png"),
    "Lasagna alla Bolognese": require("../../assets/img/dishes/LasagnaBolognese.png"),
    "Lemon Roasted Chicken": require("../../assets/img/dishes/LemonRoastedChicken.png"),
    "Mixed Grilled Meat": require("../../assets/img/dishes/GrilledMeatPotatoes.png"),
    "Mixed Grilled Seafood": require("../../assets/img/dishes/GrilledSalmon.png"),
    "Muffin Assortment": require("../../assets/img/dishes/MuffinAssortment.png"),
    "Omelette with Mushrooms": require("../../assets/img/dishes/OmeletteMushrooms.png"),
    "Onion Soup": require("../../assets/img/dishes/OnionSoup.png"),
    "Pancakes with Maple Syrup": require("../../assets/img/dishes/PancakesMapleSyrup.png"),
    "Panna Cotta": require("../../assets/img/dishes/PannaCotta.png"),
    "Panna Cotta with Mixed Berries": require("../../assets/img/dishes/PannaCottaMixedBerries.png"),
    "Panzanella": require("../../assets/img/dishes/Panzanella.png"),
    "Pasta alla Carbonara": require("../../assets/img/dishes/PastaCarbonara.png"),
    "Pasta alla Genovese": require("../../assets/img/dishes/PastaGenovese.png"),
    "Pasta with Pesto": require("../../assets/img/dishes/PastaPesto.png"),
    "Pasta with Pomodoro": require("../../assets/img/dishes/PastaPomodor.png"),
    "Pistachio Ice Cream": require("../../assets/img/dishes/PistachioIceCream.png"),
    "Pizza Capricciosa": require("../../assets/img/dishes/PizzaCapriocciosa.png"),
    "Pizza Diavola": require("../../assets/img/dishes/PizzaDiavola.png"),
    "Pizza Margherita": require("../../assets/img/dishes/PizzaMargherita.png"),
    "Pizza Quattro Stagioni": require("../../assets/img/dishes/PizzaQuattroStagioni.png"),
    "Poached Pear Salad": require("../../assets/img/dishes/PoachedPearSalad.png"),
    "Polenta and Grilled Sausage": require("../../assets/img/dishes/PolentaGrilledSausage.png"),
    "Polenta and Mushrooms": require("../../assets/img/dishes/PolentaMushrooms.png"),
    "Polenta with Grilled Sausage": require("../../assets/img/dishes/PolentaGrilledSausage.png"),
    "Polenta with Mushrooms": require("../../assets/img/dishes/PolentaMushrooms.png"),
    "Ravioli al Burro e Salvia": require("../../assets/img/dishes/RavioliBurroSalvia.png"),
    "Ravioli del Plin": require("../../assets/img/dishes/RavioliPlin.png"),
    "Ravioli di Ricotta": require("../../assets/img/dishes/RavioliRicotta.png"),
    "Ravioli di Ricotta e Spianci": require("../../assets/img/dishes/RavioliRicottaSpianci.png"),
    "Risotto al Barolo": require("../../assets/img/dishes/RisottoBarolo.png"),
    "Risotto al Nero di Seppia": require("../../assets/img/dishes/RisottoNeroSeppia.png"),
    "Risotto alla Milanese": require("../../assets/img/dishes/RisottoMilanese.png"),
    "Risotto alla Pescatora": require("../../assets/img/dishes/RisottoPescatora.png"),
    "Risotto with Lemon": require("../../assets/img/dishes/RisottoLemon.png"),
    "Risotto with Mushrooms": require("../../assets/img/dishes/RisottoMushrooms.png"),
    "Risotto with Porcini": require("../../assets/img/dishes/RisottoPorcini.png"),
    "Roast Chicken": require("../../assets/img/dishes/RoastChicken.png"),
    "Salamne di Noci": require("../../assets/img/dishes/SalameNoci.png"),
    "Seafood Risotto": require("../../assets/img/dishes/SeafoodRisotto.png"),
    "Seafood Salad": require("../../assets/img/dishes/SeafoodSalad.png"),
    "Shakshuka": require("../../assets/img/dishes/Shakshuka.png"),
    "Sliced Beef": require("../../assets/img/dishes/SlicedBeef.png"),
    "Spaghetti with Clams": require("../../assets/img/dishes/SpaghettiClams.png"),
    "Stracciatella Ice Cream": require("../../assets/img/dishes/StracciatellaIceCream.png"),
    "Tagliatelle with Mushrooms": require("../../assets/img/dishes/TagliatelleMushrooms.png"),
    "Tagliatelle with Porcini": require("../../assets/img/dishes/TagliatellePorcini.png"),
    "Tagliatelle with Ragù": require("../../assets/img/dishes/TagliatelleRagu.png"),
    "Tagliatelle with Seafood Ragù": require("../../assets/img/dishes/TagliatelleSeafoodRagu.png"),
    "Tagliatelle with Wild Boar Ragù": require("../../assets/img/dishes/TagliatelleWildBoarRagu.png"),
    "Tajarin with Truffle": require("../../assets/img/dishes/TajarinTruffle.png"),
    "Tiramisu": require("../../assets/img/dishes/Tiramisu.png"),
    "Toast with Egg and Avocado": require("../../assets/img/dishes/ToastEggAvocado.png"),
    "Tomato Soup": require("../../assets/img/dishes/TomatoSoup.png"),
    "Torta della Nonna": require("../../assets/img/dishes/TortaNonna.png"),
    "Tortellini with Broth": require("../../assets/img/dishes/TortelliniBroth.png"),
    "Uova al Poché": require("../../assets/img/dishes/UovaPoche.png"),
    "Vanilla Ice Cream": require("../../assets/img/dishes/VanillaIceCream.png"),
    "Vetetarian Lasagna": require("../../assets/img/dishes/VegetarianLasagna.png"),
    "Vitello Tonnato": require("../../assets/img/dishes/VitelloTonnato.png"),
};

export default imagesDishes;