const imageMap: { [key: string]: any } = {
    "Al Mulino Ristorante": require('../../assets/img/restaurants/AlMulinoRistorante.png'),
    "Bistrot del Centro": require('../../assets/img/restaurants/BistrotdelCentro.png'),
    "Bistrot La Vigna": require('../../assets/img/restaurants/BistrotLaVigna.png'),
    "Boccondivino": require('../../assets/img/restaurants/Boccondivino.png'),
    "Caffè dei Portici": require('../../assets/img/restaurants/AlMulinoRistorante.png'),
    "Caffè e Cucina": require('../../assets/img/restaurants/CaffèCucina.png'),
    "Cucina della Nonna": require('../../assets/img/restaurants/CucinadellaNonna.png'),
    "Cucina di Mare": require('../../assets/img/restaurants/CucinadiMare.png'),
    "Cucina di Torino": require('../../assets/img/restaurants/CucinadiTorino.png'),
    "Cucina Fiorentina": require('../../assets/img/restaurants/CucinaFiorentina.png'),
    "Gusto e Passione": require('../../assets/img/restaurants/GustoePassione.png'),
    "Il Gatto": require('../../assets/img/restaurants/IlGatto.png'),
    "Il Rifugio delle Alpi": require('../../assets/img/restaurants/IlRifugiodelleAlpi.png'),
    "L'Antica Trattoria": require('../../assets/img/restaurants/AnticaTrattoria.png'),
    "L'Osteria del Mare": require('../../assets/img/restaurants/OsteriadelMare.png'),
    "La Bottega del Gusto": require('../../assets/img/restaurants/LaBottegadelGusto.png'),
    "La Cantina del Vino": require('../../assets/img/restaurants/LaCantinadelVino.png'),
    "La Cucina di Nonna": require('../../assets/img/restaurants/LaCucinadiNonna.png'),
    "La Dolce Tavola": require('../../assets/img/restaurants/LaDolceTavola.png'),
    "La Dolce Vita": require('../../assets/img/restaurants/LaDolceVita.png'),
    "La Locanda di Torino": require('../../assets/img/restaurants/LaLocandadiTorino.png'),
    "La Piazza di Torino": require('../../assets/img/restaurants/LaPiazzadiTorino.png'),
    "La Tavola del Re": require('../../assets/img/restaurants/LaTavoladelRe.png'),
    "La Trattoria del Borgo": require('../../assets/img/restaurants/LaTrattoriadelBorgo.png'),
    "Le Delizie di Torino": require('../../assets/img/restaurants/LeDeliziediTorino.png'),
    "Le Perle di Torino": require('../../assets/img/restaurants/LePerlediTorino.png'),
    "Osteria Al Vecchio Forno": require('../../assets/img/restaurants/OsteriaAlVecchioForno.png'),
    "Osteria del Mare": require('../../assets/img/restaurants/OsteriadelMare.png'),
    "Piazza del Gusto": require('../../assets/img/restaurants/PiazzadelGusto.png'),
    "Pizzeria Da Michele": require('../../assets/img/restaurants/PizzeriaDaMichele.png'),
    "Ristorante Al Mercato": require('../../assets/img/restaurants/RistoranteAlMercato.png'),
    "Ristorante Al Tramonto": require('../../assets/img/restaurants/RistoranteAlTramonto.png'),
    "Ristorante Al Verde": require('../../assets/img/restaurants/RistoranteAlVerde.png'),
    "Ristorante Eleganza": require('../../assets/img/restaurants/RistoranteEleganza.png'),
    "Ristorante Galleria": require('../../assets/img/restaurants/RistoranteGalleria.png'),
    "Ristorante Il Giardino": require('../../assets/img/restaurants/RistoranteIlGiardino.png'),
    "Ristorante Il Piemonte": require('../../assets/img/restaurants/AlMulinoRistorante.png'),
    "Ristorante Accademia": require('../../assets/img/restaurants/RistoranteAccademia.png'),
    "Ristorante Mare e Monti": require('../../assets/img/restaurants/RistoranteMareeMonti.png'),
    "Ristorante Sapore di Mare": require('../../assets/img/restaurants/RistoranteSaporediMare.png'),
    "Sapore e Passione": require('../../assets/img/restaurants/SaporeePassione.png'),
    "Sogno di Torino": require('../../assets/img/restaurants/SognodiTorino.png'),
    "Trattoria del Buon Gusto": require('../../assets/img/restaurants/TrattoriadelBuonGusto.png'),
    "Trattoria Le Colline": require('../../assets/img/restaurants/TrattoriaLeColline.png'),
    "Trattoria San Giovanni": require('../../assets/img/restaurants/TrattoriaSanGiovanni.png'),
    "Trattoria Vecchia Torino": require('../../assets/img/restaurants/TrattoriaVecchiaTorino.png')
  };
  
  export default imageMap;